### ISSUE TITLE
bynder-input.json's portalDomain not doing anything

### ISSUE THREAD

**Issue by mix3d** [sanity-io/sanity-plugin-bynder-input#6]
I have added the portalDomain as documented in the README, but I am still greeted with an empty "Connect your brand portal" message. 

<img width="441" alt="image" src="https://user-images.githubusercontent.com/1474137/167154667-f68e91ec-45af-4116-be48-c0ef8418bf07.png">

What do I need to do to have a default value and skip this step?

If I enter a value here, it is saved to localStorage key `cvad` and pre-filled the next time the portal window opens but I still have to press the "connect" button; I am looking for "always use this value" behavior and going straight to our brand's domain authentication.

**Comment by sjelfull** [comment]
The issue here seems to be that Bynder changed the prop `defaultDomain` into an object, `portal: { url: '...' }`.

Got a fix for tihs.
